import React, { createContext, useContext, useState, useEffect } from 'react';

const AppContext = createContext();

export const useApp = () => {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
};

export const AppProvider = ({ children }) => {
  const [isDarkMode, setIsDarkMode] = useState(() => {
    // Check localStorage first, then system preference
    const saved = localStorage.getItem('darkMode');
    if (saved !== null) {
      return JSON.parse(saved);
    }
    return window.matchMedia('(prefers-color-scheme: dark)').matches;
  });

  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'ar';
  });

  const [isLanguageDropdownOpen, setIsLanguageDropdownOpen] = useState(false);

  // Apply initial dark mode class on mount
  useEffect(() => {
    if (isDarkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, []);

  const languages = [
    { code: 'en', name: 'English', flag: '🇺🇸' },
    { code: 'ar', name: 'العربية', flag: '🇸🇦' },
    { code: 'fr', name: 'Français', flag: '🇫🇷' }
  ];

  // Clean translations object with no duplicates
  const translations = {
    en: {
      // Navigation
      home: 'Home',
      hajjUmrah: 'Hajj & Umrah',
      globalTourism: 'Global Tourism',
      contact: 'Contact',
      bookNow: 'Book Now',
      account: 'Account',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      selectLanguage: 'Select Language',
      
      // Homepage
      heroTitle: 'Your Journey Begins Here',
      heroSubtitle: 'Experience the world\'s most sacred pilgrimages and breathtaking destinations with Al-Hijrah Tourism - your trusted partner in spiritual and cultural journeys.',
      exploreHajjUmrah: 'Explore Hajj & Umrah',
      discoverGlobalTours: 'Discover Global Tours',
      ourServices: 'Our Services',
      servicesSubtitle: 'We provide comprehensive travel solutions tailored to your spiritual and cultural needs',
      hajjUmrahService: 'Hajj & Umrah',
      hajjUmrahDesc: 'Complete spiritual journeys with expert guidance and premium accommodations',
      globalTourismService: 'Global Tourism',
      globalTourismDesc: 'Explore the world with our carefully curated travel packages and experiences',
      expertGuidance: 'Expert Guidance',
      expertGuidanceDesc: 'Professional travel consultants to ensure your journey is seamless and memorable',
      bestPrices: 'Best Prices',
      bestPricesDesc: 'Competitive pricing with no hidden fees and flexible payment options',
      specialOffers: 'Special Offers',
      specialOffersSubtitle: 'Don\'t miss out on these limited-time deals',
      whyChooseUs: 'Why Choose Al-Hijrah Tourism?',
      expertGuidanceFeature: 'Expert Guidance',
      expertGuidanceFeatureDesc: 'Our experienced team provides personalized guidance for every step of your journey',
      premiumAccommodations: 'Premium Accommodations',
      premiumAccommodationsDesc: 'Stay in carefully selected hotels and accommodations for maximum comfort',
      support247: '24/7 Support',
      support247Desc: 'Round-the-clock assistance to ensure your journey is smooth and worry-free',
      readyToStart: 'Ready to Start Your Journey?',
      readyToStartSubtitle: 'Contact us today to plan your perfect spiritual or cultural journey',
      bookYourTrip: 'Book Your Trip',
      getInTouch: 'Get in Touch',
      
      // Hajj & Umrah Page
      hajjUmrahTitle: 'Hajj & Umrah Programs',
      hajjUmrahSubtitle: 'Embark on your spiritual journey with our carefully crafted Hajj and Umrah packages. Experience the sacred pilgrimage with comfort, guidance, and peace of mind.',
      packageType: 'Package Type',
      allTypes: 'All Types',
      hajj: 'Hajj',
      umrah: 'Umrah',
      duration: 'Duration',
      allDurations: 'All Durations',
      shortDuration: '1-7 days',
      mediumDuration: '8-10 days',
      longDuration: '11+ days',
      priceRange: 'Price Range',
      allPrices: 'All Prices',
      budgetPrice: 'Under $2,000',
      midPrice: '$2,000 - $3,500',
      premiumPrice: 'Above $3,500',
      availablePackages: 'Available Packages',
      choosePackages: 'Choose from our carefully selected Hajj and Umrah packages',
      noPackagesFound: 'No packages found',
      tryAdjustingFilters: 'Try adjusting your filters to see more options',
      packageIncludes: 'Package includes:',
      moreFeatures: 'more features',
      viewDetails: 'View Details',
      reviews: 'reviews',
      
      // Package Types
      premiumHajjPackage: 'Premium Hajj Package',
      standardHajjPackage: 'Standard Hajj Package',
      budgetHajjPackage: 'Budget Hajj Package',
      familyHajjPackage: 'Family Hajj Package',
      luxuryUmrahPackage: 'Luxury Umrah Package',
      standardUmrahPackage: 'Standard Umrah Package',
      budgetUmrahPackage: 'Budget Umrah Package',
      familyUmrahPackage: 'Family Umrah Package',
      quickUmrahPackage: 'Quick Umrah Package',
      economyHajjPackage: 'Economy Hajj Package 2024',
      
      // Package Descriptions
      premiumHajjDesc: 'Complete Hajj experience with 5-star accommodation in Makkah and Madinah',
      standardHajjDesc: 'Comfortable Hajj journey with quality accommodation and essential services',
      luxuryUmrahDesc: 'Premium Umrah experience with luxury accommodations and personalized service',
      standardUmrahDesc: 'Comfortable Umrah journey with quality accommodation and essential services',
      budgetUmrahDesc: 'Affordable Umrah package with basic accommodation and essential services',
      familyHajjDesc: 'Family-friendly Hajj package with spacious accommodations and child-friendly services',
      familyUmrahDesc: 'Perfect for families with children, including family-friendly accommodations',
      quickUmrahDesc: 'Short and sweet Umrah journey for those with limited time',
      
      // Package Features
      roundTripFlights: 'Round-trip flights',
      fiveStarMakkah: '5-star hotel in Makkah (5 nights)',
      fourStarMakkah: '4-star hotel in Makkah (5 nights)',
      threeStarMakkah: '3-star hotel in Makkah (5 nights)',
      fiveStarMadinah: '5-star hotel in Madinah (5 nights)',
      fourStarMadinah: '4-star hotel in Madinah (5 nights)',
      threeStarMadinah: '3-star hotel in Madinah (5 nights)',
      allMealsIncluded: 'All meals included',
      breakfastIncluded: 'Breakfast included',
      expertGuide: 'Expert guide throughout',
      expertGuideBasic: 'Expert guide',
      transportationIncluded: 'Transportation included',
      groupSize: 'Small group size (max 20)',
      familyServices: 'Family-friendly services',
      childCare: 'Child care services',
      
      // Global Tourism
      globalTourismTitle: 'Global Tourism Packages',
      globalTourismSubtitle: 'Discover the world with our carefully curated travel experiences. From cultural heritage tours to adventure expeditions, we offer unforgettable journeys across the globe.',
      
      // Booking Form
      serviceSelection: 'Service Selection',
      personalInformation: 'Personal Information',
      travelDetails: 'Travel Details',
      emergencyContact: 'Emergency Contact',
      paymentConfirmation: 'Payment Confirmation',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      phone: 'Phone',
      dateOfBirth: 'Date of Birth',
      nationality: 'Nationality',
      passportNumber: 'Passport Number',
      passportExpiry: 'Passport Expiry',
      departureCity: 'Departure City',
      preferredDepartureDate: 'Preferred Departure Date',
      returnDate: 'Return Date',
      numberOfTravelers: 'Number of Travelers',
      roomType: 'Room Type',
      specialRequests: 'Special Requests',
      travelInsurance: 'Travel Insurance',
      visaAssistance: 'Visa Assistance',
      airportTransfer: 'Airport Transfer',
      emergencyContactName: 'Emergency Contact Name',
      emergencyContactPhone: 'Emergency Contact Phone',
      emergencyContactRelation: 'Emergency Contact Relation',
      paymentMethod: 'Payment Method',
      agreeToTerms: 'Agree to Terms',
      singleRoom: 'Single Room',
      doubleRoom: 'Double Room',
      tripleRoom: 'Triple Room',
      quadRoom: 'Quad Room',
      extraBaggageAllowance: 'Extra Baggage Allowance',
      seatSelection: 'Seat Selection',
      mealUpgrade: 'Meal Upgrade',
      inFlightWifi: 'In-Flight WiFi',
      creditCard: 'Credit Card',
      debitCard: 'Debit Card',
      bankTransfer: 'Bank Transfer',
      installments: 'Installments',
      
      // Contact Us
      contactUs: 'Contact Us',
      contactUsSubtitle: 'Get in touch with us for any questions or assistance with your travel plans',
      name: 'Name',
      subject: 'Subject',
      message: 'Message',
      inquiryType: 'Inquiry Type',
      generalInquiry: 'General Inquiry',
      bookingInquiry: 'Booking Inquiry',
      supportRequest: 'Support Request',
      feedback: 'Feedback',
      other: 'Other',
      submit: 'Submit',
      contactInfo: 'Contact Information',
      address: 'Address',
      emailAddress: 'Email Address',
      phoneNumber: 'Phone Number',
      workingHours: 'Working Hours',
      mondayToFriday: 'Monday to Friday',
      saturday: 'Saturday',
      sunday: 'Sunday',
      contactMethods: 'Contact Methods',
      
      // Authentication
      login: 'Login',
      signup: 'Sign Up',
      logout: 'Logout',
      adminLogin: 'Admin Login',
      adminLoginSubtitle: 'Access the admin dashboard',
      demoCredentials: 'Demo Credentials',
      password: 'Password',
      rememberMe: 'Remember Me',
      forgotPassword: 'Forgot Password?',
      backToWebsite: 'Back to Website',
      signingIn: 'Signing In...',
      signIn: 'Sign In',
      firstNameRequired: 'First name is required',
      lastNameRequired: 'Last name is required',
      emailRequired: 'Email is required',
      emailInvalid: 'Email is invalid',
      phoneRequired: 'Phone number is required',
      phoneInvalid: 'Phone number is invalid',
      passwordRequired: 'Password is required',
      passwordMinLength: 'Password must be at least 6 characters',
      passwordMinLength8: 'Password must be at least 8 characters',
      passwordComplexity: 'Password must contain uppercase, lowercase, number, and special character',
      confirmPasswordRequired: 'Confirm password is required',
      passwordsDoNotMatch: 'Passwords do not match',
      mustAgreeToTerms: 'You must agree to the terms and conditions',
      invalidCredentials: 'Invalid credentials',
      loginError: 'Login error occurred',
      
      // Profile
      profile: 'Profile',
      profileSettings: 'Profile Settings',
      personalInfo: 'Personal Information',
      bookingHistory: 'Booking History',
      preferences: 'Preferences',
      notifications: 'Notifications',
      privacy: 'Privacy',
      security: 'Security',
      editProfile: 'Edit Profile',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      
      // Admin Dashboard
      adminDashboard: 'Admin Dashboard',
      dashboardOverview: 'Dashboard Overview',
      packageManagement: 'Package Management',
      bookingManagement: 'Booking Management',
      userManagement: 'User Management',
      contentManagement: 'Content Management',
      analyticsDashboard: 'Analytics Dashboard',
      settingsPanel: 'Settings Panel',
      totalBookings: 'Total Bookings',
      totalRevenue: 'Total Revenue',
      activeUsers: 'Active Users',
      pendingBookings: 'Pending Bookings',
      recentBookings: 'Recent Bookings',
      topPerformingPackages: 'Top Performing Packages',
      customerInsights: 'Customer Insights',
      newCustomers: 'New Customers',
      returningCustomers: 'Returning Customers',
      averageAge: 'Average Age',
      topCountries: 'Top Countries',
      generalSettings: 'General Settings',
      appearance: 'Appearance',
      emailSettings: 'Email Settings',
      backupRestore: 'Backup & Restore',
      siteName: 'Site Name',
      siteDescription: 'Site Description',
      contactEmail: 'Contact Email',
      contactPhone: 'Contact Phone',
      currency: 'Currency',
      timezone: 'Timezone',
      dateFormat: 'Date Format',
      defaultLanguage: 'Default Language',
      theme: 'Theme',
      brandColors: 'Brand Colors',
      primary: 'Primary',
      secondary: 'Secondary',
      accent: 'Accent',
      background: 'Background',
      emailNotifications: 'Email Notifications',
      smsNotifications: 'SMS Notifications',
      maintenanceMode: 'Maintenance Mode',
      allowUserRegistration: 'Allow User Registration',
      requireEmailVerification: 'Require Email Verification',
      maximumFileSize: 'Maximum File Size',
      allowedFileTypes: 'Allowed File Types',
      smtpHost: 'SMTP Host',
      smtpPort: 'SMTP Port',
      smtpUsername: 'SMTP Username',
      smtpPassword: 'SMTP Password',
      fromEmailAddress: 'From Email Address',
      fromName: 'From Name',
      testEmailConfiguration: 'Test Email Configuration',
      saveEmailSettings: 'Save Email Settings',
      createBackup: 'Create Backup',
      restoreBackup: 'Restore Backup',
      backupHistory: 'Backup History',
      createBackupNow: 'Create Backup Now',
      download: 'Download',
      
      // Common Actions
      add: 'Add',
      edit: 'Edit',
      delete: 'Delete',
      view: 'View',
      save: 'Save',
      confirm: 'Confirm',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      export: 'Export',
      import: 'Import',
      refresh: 'Refresh',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      warning: 'Warning',
      info: 'Information',
      
      // Status
      active: 'Active',
      inactive: 'Inactive',
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      cancelled: 'Cancelled',
      completed: 'Completed',
      inProgress: 'In Progress',
      draft: 'Draft',
      published: 'Published',
      
      // User Types
      admin: 'Admin',
      staff: 'Staff',
      userType: 'User Type',
      fullName: 'Full Name',
      joinDate: 'Join Date',
      lastLogin: 'Last Login',
      status: 'Status',
      role: 'Role',
      permissions: 'Permissions',
      department: 'Department',
      
      // Booking Status
      bookingId: 'Booking ID',
      bookingDate: 'Booking Date',
      travelDate: 'Travel Date',
      travelers: 'Travelers',
      amount: 'Amount',
      payment: 'Payment',
      actions: 'Actions',
      customer: 'Customer',
      package: 'Package',
      price: 'Price',
      revenue: 'Revenue',
      bookings: 'Bookings',
      
      // Content Management
      addContent: 'Add Content',
      contentType: 'Content Type',
      title: 'Title',
      slug: 'Slug',
      content: 'Content',
      excerpt: 'Excerpt',
      featuredImage: 'Featured Image',
      tags: 'Tags',
      categories: 'Categories',
      publishDate: 'Publish Date',
      views: 'Views',
      uploadMedia: 'Upload Media',
      mediaLibrary: 'Media Library',
      translationKey: 'Translation Key',
      lastModified: 'Last Modified',
      modifiedBy: 'Modified By',
      translations: 'Translations',
      pages: 'Pages',
      totalPageViews: 'Total Page Views',
      publishedPages: 'Published Pages',
      draftPages: 'Draft Pages',
      
      // Footer
      footerDescription: 'Your trusted partner for Hajj, Umrah, and global tourism experiences. We provide exceptional service and unforgettable journeys that create lasting memories.',
      quickLinks: 'Quick Links',
      aboutUs: 'About Us',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      facebook: 'Facebook',
      instagram: 'Instagram',
      twitter: 'Twitter',
      linkedin: 'LinkedIn',
      youtube: 'YouTube',
      copyright: '© 2025 ZoukhDev. All rights reserved.',
      
      // Common
      overview: 'Overview',
      details: 'Details',
      totalSpent: 'Total Spent',
      staffMembers: 'Staff Members',
      addUser: 'Add User',
      
      // Special Offers
      earlyBirdHajj2024: 'Early Bird Hajj 2024',
      earlyBirdHajjDesc: 'Book your Hajj journey now and save up to 15% on premium packages',
      umrahSpecialPackage: 'Umrah Special Package',
      umrahSpecialDesc: 'Complete Umrah experience with 5-star accommodation and guided tours',
      europeanSummerTour: 'European Summer Tour',
      europeanSummerDesc: 'Explore the beauty of Europe with our curated summer packages',
      march31_2024: 'March 31, 2026',
      april15_2024: 'April 15, 2026',
      may30_2024: 'May 30, 2026',
      
      // Booking Form Translations
      bookYourJourney: 'Book Your Journey',
      completeFormToReserve: 'Complete the form to reserve your spot',
      serviceSelection: 'Service Selection',
      personalInformation: 'Personal Information',
      travelDetails: 'Travel Details',
      emergencyContact: 'Emergency Contact',
      paymentConfirmation: 'Payment Confirmation',
      submitBooking: 'Submit Booking',
      selectYourService: 'Select Your Service',
      serviceType: 'Service Type',
      selectPackage: 'Select Package',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      phone: 'Phone',
      departureCity: 'Departure City',
      preferredDepartureDate: 'Preferred Departure Date',
      returnDate: 'Return Date',
      numberOfTravelers: 'Number of Travelers',
      roomType: 'Room Type',
      singleRoom: 'Single Room',
      doubleRoom: 'Double Room',
      tripleRoom: 'Triple Room',
      quadRoom: 'Quad Room',
      specialRequests: 'Special Requests',
      travelInsurance: 'Travel Insurance',
      visaAssistance: 'Visa Assistance',
      airportTransfer: 'Airport Transfer',
      additionalServices: 'Additional Services',
      agreeToTerms: 'I agree to the terms and conditions',
      nextStep: 'Next Step',
      previousStep: 'Previous Step',
      totalCost: 'Total Cost',
      perPerson: 'per person',
      selectDate: 'Select Date',
      enterCity: 'Enter City',
      enterPhone: 'Enter Phone',
      enterEmail: 'Enter Email',
      required: 'Required',
      optional: 'Optional',
      
      // Additional Form Field Translations
      selectServiceType: 'Select Service Type',
      package: 'Package',
      phoneNumber: 'Phone Number',
      person: 'person',
      people: 'people',
      selectRoomType: 'Select Room Type',
      bookingSummary: 'Booking Summary',
      travelers: 'Travelers',
      basePrice: 'Base Price',
      total: 'Total',
      previous: 'Previous',
      next: 'Next',
      
      // Additional Services
      extraBaggageAllowance: 'Extra Baggage Allowance',
      seatSelection: 'Seat Selection',
      mealUpgrade: 'Meal Upgrade',
      inFlightWifi: 'In-Flight WiFi',
      
      // Payment Methods
      creditCard: 'Credit Card',
      debitCard: 'Debit Card',
      bankTransfer: 'Bank Transfer',
      installments: 'Installments',
      
      // Placeholders and Help Text
      placeholderDepartureCity: 'e.g., New York, London, Dubai',
      placeholderSpecialRequests: 'Any special dietary requirements, accessibility needs, or other requests...',
      
      // Service Types
      hajj: 'Hajj',
      umrah: 'Umrah',
      globalTourism: 'Global Tourism',
      
      // Package Names
      premiumHajjPackage2024: 'Premium Hajj Package 2024',
      standardHajjPackage2024: 'Standard Hajj Package 2024',
      economyHajjPackage2024: 'Economy Hajj Package 2024',
      luxuryUmrahPackage: 'Luxury Umrah Package',
      familyUmrahPackage: 'Family Umrah Package',
      quickUmrahPackage: 'Quick Umrah Package',
      europeanCulturalHeritageTour: 'European Cultural Heritage Tour',
      southeastAsiaAdventure: 'Southeast Asia Adventure',
      africanSafariExperience: 'African Safari Experience',
      
      // Admin Dashboard Translations
      dashboardOverview: 'Dashboard Overview',
      totalBookings: 'Total Bookings',
      totalRevenue: 'Total Revenue',
      activePackages: 'Active Packages',
      registeredUsers: 'Registered Users',
      recentBookings: 'Recent Bookings',
      topPackages: 'Top Packages',
      revenueChart: 'Revenue Chart',
      bookingTrends: 'Booking Trends',
      monthlyRevenue: 'Monthly Revenue',
      bookingStatus: 'Booking Status',
      pendingBookings: 'Pending Bookings',
      confirmedBookings: 'Confirmed Bookings',
      cancelledBookings: 'Cancelled Bookings',
      completedBookings: 'Completed Bookings',
      
      // Package Management
      packageManagement: 'Package Management',
      addNewPackage: 'Add New Package',
      packageName: 'Package Name',
      packageDescription: 'Package Description',
      packagePrice: 'Package Price',
      packageDuration: 'Package Duration',
      packageStatus: 'Package Status',
      active: 'Active',
      inactive: 'Inactive',
      featured: 'Featured',
      editPackage: 'Edit Package',
      deletePackage: 'Delete Package',
      packageDetails: 'Package Details',
      inclusions: 'Inclusions',
      exclusions: 'Exclusions',
      itinerary: 'Itinerary',
      requirements: 'Requirements',
      availability: 'Availability',
      
      // Booking Management
      bookingManagement: 'Booking Management',
      bookingId: 'Booking ID',
      customerName: 'Customer Name',
      packageName: 'Package Name',
      bookingDate: 'Booking Date',
      travelDate: 'Travel Date',
      totalAmount: 'Total Amount',
      bookingStatus: 'Booking Status',
      paymentStatus: 'Payment Status',
      pending: 'Pending',
      confirmed: 'Confirmed',
      cancelled: 'Cancelled',
      completed: 'Completed',
      paid: 'Paid',
      unpaid: 'Unpaid',
      refunded: 'Refunded',
      failed: 'Failed',
      viewBooking: 'View Booking',
      editBooking: 'Edit Booking',
      updateStatus: 'Update Status',
      sendNotification: 'Send Notification',
      
      // User Management
      userManagement: 'User Management',
      addNewUser: 'Add New User',
      userRole: 'User Role',
      admin: 'Admin',
      staff: 'Staff',
      user: 'User',
      userStatus: 'User Status',
      lastLogin: 'Last Login',
      joinDate: 'Join Date',
      editUser: 'Edit User',
      deleteUser: 'Delete User',
      userPermissions: 'User Permissions',
      canManageUsers: 'Can Manage Users',
      canManageBookings: 'Can Manage Bookings',
      canManagePackages: 'Can Manage Packages',
      canManageContent: 'Can Manage Content',
      canViewAnalytics: 'Can View Analytics',
      canManageSettings: 'Can Manage Settings',
      
      // Content Management
      contentManagement: 'Content Management',
      pages: 'Pages',
      addNewPage: 'Add New Page',
      pageTitle: 'Page Title',
      pageContent: 'Page Content',
      pageStatus: 'Page Status',
      published: 'Published',
      draft: 'Draft',
      editPage: 'Edit Page',
      deletePage: 'Delete Page',
      translations: 'Translations',
      addTranslation: 'Add Translation',
      translationKey: 'Translation Key',
      englishText: 'English Text',
      arabicText: 'Arabic Text',
      frenchText: 'French Text',
      editTranslation: 'Edit Translation',
      deleteTranslation: 'Delete Translation',
      
      // Analytics & Reports
      analyticsReports: 'Analytics & Reports',
      revenueAnalytics: 'Revenue Analytics',
      bookingAnalytics: 'Booking Analytics',
      userAnalytics: 'User Analytics',
      packageAnalytics: 'Package Analytics',
      generateReport: 'Generate Report',
      reportType: 'Report Type',
      dateRange: 'Date Range',
      exportReport: 'Export Report',
      downloadReport: 'Download Report',
      reportPeriod: 'Report Period',
      lastWeek: 'Last Week',
      lastMonth: 'Last Month',
      lastQuarter: 'Last Quarter',
      lastYear: 'Last Year',
      customRange: 'Custom Range',
      
      // Settings
      settings: 'Settings',
      generalSettings: 'General Settings',
      siteSettings: 'Site Settings',
      emailSettings: 'Email Settings',
      securitySettings: 'Security Settings',
      notificationSettings: 'Notification Settings',
      backupSettings: 'Backup Settings',
      siteName: 'Site Name',
      siteDescription: 'Site Description',
      contactEmail: 'Contact Email',
      contactPhone: 'Contact Phone',
      address: 'Address',
      currency: 'Currency',
      timezone: 'Timezone',
      dateFormat: 'Date Format',
      language: 'Language',
      enableNotifications: 'Enable Notifications',
      emailNotifications: 'Email Notifications',
      smsNotifications: 'SMS Notifications',
      maintenanceMode: 'Maintenance Mode',
      allowRegistration: 'Allow Registration',
      requireEmailVerification: 'Require Email Verification',
      maxFileSize: 'Max File Size',
      allowedFileTypes: 'Allowed File Types',
      saveSettings: 'Save Settings',
      resetSettings: 'Reset Settings',
      backupData: 'Backup Data',
      restoreData: 'Restore Data',
      
      // Additional Dashboard Texts
      fromLastMonth: 'from Last Month',
      fromLastPeriod: 'from Last Period',
      confirmed: 'Confirmed',
      pending: 'Pending',
      cancelled: 'Cancelled',
      premiumHajjPackage2024: 'Premium Hajj Package 2024',
      luxuryUmrahPackage: 'Luxury Umrah Package',
      europeanCulturalHeritageTour: 'European Cultural Heritage Tour',
      familyUmrahPackage: 'Family Umrah Package',
      viewBookings: 'View Bookings',
      manageYourTravelPackages: 'Manage Your Travel Packages',
      edit: 'Edit',
      view: 'View',
      delete: 'Delete',
      duration: 'Duration',
      price: 'Price',
      bookings: 'Bookings',
      revenue: 'Revenue',
      status: 'Status',
      actions: 'Actions',
      active: 'Active',
      manageCustomerBookings: 'Manage Customer Bookings',
      amount: 'Amount',
      payment: 'Payment',
      manageCustomersAndStaff: 'Manage Customers and Staff',
      totalCustomers: 'Total Customers',
      activeCustomers: 'Active Customers',
      staffMembers: 'Staff Members',
      trackBusinessPerformance: 'Track Business Performance',
      bookingsByType: 'Bookings by Type',
      topPerformingPackages: 'Top Performing Packages',
      customerInsights: 'Customer Insights',
      newCustomers: 'New Customers',
      returningCustomers: 'Returning Customers',
      averageAge: 'Average Age',
      topCountries: 'Top Countries',
      configureWebsiteSettings: 'Configure Website Settings',
      appearance: 'Appearance',
      notifications: 'Notifications',
      security: 'Security',
      emailSettings: 'Email Settings',
      backupRestore: 'Backup & Restore',
      allowUserRegistration: 'Allow User Registration',
      allowNewUsersToRegister: 'Allow new users to register accounts',
      requireEmailVerification: 'Require users to verify their email addresses',
      
      // Additional Status and Value Translations
      paid: 'Paid',
      refunded: 'Refunded',
      active: 'Active',
      inactive: 'Inactive',
      avgBookingValue: 'Average Booking Value',
      confirmed: 'Confirmed',
      pending: 'Pending',
      cancelled: 'Cancelled',
      modifier: 'Modifier',
      copy: 'Copy',
      conversionRate: 'Conversion Rate',
      temporarilyDisablePublicAccess: 'Temporarily disable public access to the website',
      allowNewUsersToRegister: 'Allow new users to register accounts',
      requireUsersToVerifyEmail: 'Require users to verify their email addresses',
      fileUploadSettings: 'File Upload Settings',
      maximumFileSize: 'Maximum File Size',
      receiveEmailNotifications: 'Receive email notifications for important events',
      receiveSmsNotifications: 'Receive SMS notifications for urgent updates'
    },
    
    ar: {
      // Navigation
      home: 'الرئيسية',
      hajjUmrah: 'الحج والعمرة',
      globalTourism: 'السياحة العالمية',
      contact: 'اتصل بنا',
      bookNow: 'احجز الآن',
      account: 'الحساب',
      darkMode: 'الوضع المظلم',
      lightMode: 'الوضع المضيء',
      selectLanguage: 'اختر اللغة',
      
      // Homepage
      heroTitle: 'رحلتك تبدأ من هنا',
      heroSubtitle: 'بداية الطريق الى بيت الله الحرام لاداء منساك الحج و العمرة',
      exploreHajjUmrah: 'استكشف الحج والعمرة',
      discoverGlobalTours: 'اكتشف الجولات العالمية',
      ourServices: 'خدماتنا',
      servicesSubtitle: 'نوفر حلول سفر شاملة مصممة خصيصاً لاحتياجاتك الروحية والثقافية',
      hajjUmrahService: 'الحج والعمرة',
      hajjUmrahDesc: 'رحلات روحية كاملة مع إرشاد خبير وإقامة فاخرة',
      globalTourismService: 'السياحة العالمية',
      globalTourismDesc: 'استكشف العالم مع حزم السفر وال experiences التي نختارها بعناية',
      expertGuidance: 'إرشاد خبير',
      expertGuidanceDesc: 'مستشارو سفر محترفون لضمان أن تكون رحلتك سلسة ومليئة بالذكريات',
      bestPrices: 'أفضل الأسعار',
      bestPricesDesc: 'أسعار تنافسية بدون رسوم مخفية وخيارات دفع مرنة',
      specialOffers: 'عروض خاصة',
      specialOffersSubtitle: 'لا تفوت هذه الصفقات المحدودة الوقت',
      whyChooseUs: 'لماذا تختار الحجرة للسياحة؟',
      expertGuidanceFeature: 'إرشاد خبير',
      expertGuidanceFeatureDesc: 'فريقنا ذو الخبرة يوفر إرشاداً شخصياً لكل خطوة في رحلتك',
      premiumAccommodations: 'إقامة فاخرة',
      premiumAccommodationsDesc: 'اقض في فنادق وإقامة مختارة بعناية لأقصى راحة',
      support247: 'دعم على مدار الساعة',
      support247Desc: 'مساعدة على مدار الساعة لضمان أن تكون رحلتك سلسة وخالية من القلق',
      readyToStart: 'مستعد لبدء رحلتك؟',
      readyToStartSubtitle: 'اتصل بنا اليوم لتخطيط رحلتك الروحية أو الثقافية المثالية',
      bookYourTrip: 'احجز رحلتك',
      getInTouch: 'تواصل معنا',
      
      // Additional Arabic translations (no duplicates)
      visaAssistance: 'مساعدة التأشيرة',
      cancel: 'إلغاء',
      customer: 'العميل',
      emailAddress: 'عنوان البريد الإلكتروني',
      phoneNumber: 'رقم الهاتف',
      email: 'البريد الإلكتروني',
      totalSpent: 'إجمالي المصروف',
      fullName: 'الاسم الكامل',
      address: 'العنوان',
      overview: 'نظرة عامة',
      totalBookings: 'إجمالي الحجوزات',
      recentBookings: 'الحجوزات الأخيرة',
      bookingId: 'رقم الحجز',
      travelDate: 'تاريخ السفر',
      packageType: 'نوع الباقة',
      userType: 'نوع المستخدم',
      addUser: 'إضافة مستخدم',
      totalPageViews: 'إجمالي مشاهدات الصفحة',
      publishedPages: 'الصفحات المنشورة',
      draftPages: 'الصفحات المسودة',
      
      // Special Offers
      earlyBirdHajj2024: 'الحجز المبكر للحج 2026',
      earlyBirdHajjDesc: 'احجز رحلة الحج الآن ووفر حتى 15% على الباقات المميزة',
      umrahSpecialPackage: 'باقة العمرة الخاصة',
      umrahSpecialDesc: 'تجربة عمرة كاملة مع إقامة فندقية 5 نجوم وجولات مرشدة',
      europeanSummerTour: 'جولة الصيف الأوروبية',
      europeanSummerDesc: 'استكشف جمال أوروبا مع باقات الصيف المختارة بعناية',
      march31_2024: '31 مارس 2026',
      april15_2024: '15 أبريل 2026',
      may30_2024: '30 مايو 2026',
      
      // Booking Form Translations
      bookYourJourney: 'احجز رحلتك',
      completeFormToReserve: 'أكمل النموذج للحجز',
      serviceSelection: 'اختيار الخدمة',
      personalInformation: 'المعلومات الشخصية',
      travelDetails: 'تفاصيل السفر',
      emergencyContact: 'جهة الاتصال في الطوارئ',
      paymentConfirmation: 'تأكيد الدفع',
      submitBooking: 'إرسال الحجز',
      selectYourService: 'اختر خدمتك',
      serviceType: 'نوع الخدمة',
      selectPackage: 'اختر الباقة',
      firstName: 'الاسم الأول',
      lastName: 'اسم العائلة',
      email: 'البريد الإلكتروني',
      phone: 'رقم الهاتف',
      departureCity: 'مدينة المغادرة',
      preferredDepartureDate: 'تاريخ المغادرة المفضل',
      returnDate: 'تاريخ العودة',
      numberOfTravelers: 'عدد المسافرين',
      roomType: 'نوع الغرفة',
      singleRoom: 'غرفة مفردة',
      doubleRoom: 'غرفة مزدوجة',
      tripleRoom: 'غرفة ثلاثية',
      quadRoom: 'غرفة رباعية',
      specialRequests: 'طلبات خاصة',
      travelInsurance: 'تأمين السفر',
      visaAssistance: 'مساعدة التأشيرة',
      airportTransfer: 'نقل المطار',
      additionalServices: 'خدمات إضافية',
      agreeToTerms: 'أوافق على الشروط والأحكام',
      nextStep: 'الخطوة التالية',
      previousStep: 'الخطوة السابقة',
      totalCost: 'التكلفة الإجمالية',
      perPerson: 'للشخص الواحد',
      selectDate: 'اختر التاريخ',
      enterCity: 'أدخل المدينة',
      enterPhone: 'أدخل رقم الهاتف',
      enterEmail: 'أدخل البريد الإلكتروني',
      required: 'مطلوب',
      optional: 'اختياري',
      
      // Additional Form Field Translations
      selectServiceType: 'اختر نوع الخدمة',
      package: 'الباقة',
      phoneNumber: 'رقم الهاتف',
      person: 'شخص',
      people: 'أشخاص',
      selectRoomType: 'اختر نوع الغرفة',
      bookingSummary: 'ملخص الحجز',
      travelers: 'المسافرون',
      basePrice: 'السعر الأساسي',
      total: 'المجموع',
      previous: 'السابق',
      next: 'التالي',
      
      // Additional Services
      extraBaggageAllowance: 'بدل أمتعة إضافي',
      seatSelection: 'اختيار المقعد',
      mealUpgrade: 'ترقية الوجبات',
      inFlightWifi: 'واي فاي الطيران',
      
      // Payment Methods
      creditCard: 'بطاقة ائتمان',
      debitCard: 'بطاقة خصم',
      bankTransfer: 'تحويل بنكي',
      installments: 'تقسيط',
      
      // Placeholders and Help Text
      placeholderDepartureCity: 'مثال: الرياض، دبي، لندن',
      placeholderSpecialRequests: 'أي متطلبات غذائية خاصة، احتياجات إمكانية الوصول، أو طلبات أخرى...',
      
      // Service Types
      hajj: 'الحج',
      umrah: 'العمرة',
      globalTourism: 'السياحة العالمية',
      
      // Package Names
      premiumHajjPackage2024: 'باقة الحج المميزة 2024',
      standardHajjPackage2024: 'باقة الحج القياسية 2024',
      economyHajjPackage2024: 'باقة الحج الاقتصادية 2024',
      luxuryUmrahPackage: 'باقة العمرة الفاخرة',
      familyUmrahPackage: 'باقة العمرة العائلية',
      quickUmrahPackage: 'باقة العمرة السريعة',
      europeanCulturalHeritageTour: 'جولة التراث الثقافي الأوروبي',
      southeastAsiaAdventure: 'مغامرة جنوب شرق آسيا',
      africanSafariExperience: 'تجربة السفاري الأفريقية',
      
      // Admin Dashboard Translations
      dashboardOverview: 'نظرة عامة على لوحة التحكم',
      totalBookings: 'إجمالي الحجوزات',
      totalRevenue: 'إجمالي الإيرادات',
      activePackages: 'الباقات النشطة',
      registeredUsers: 'المستخدمون المسجلون',
      recentBookings: 'الحجوزات الأخيرة',
      topPackages: 'أفضل الباقات',
      revenueChart: 'رسم بياني للإيرادات',
      bookingTrends: 'اتجاهات الحجز',
      monthlyRevenue: 'الإيرادات الشهرية',
      bookingStatus: 'حالة الحجز',
      pendingBookings: 'الحجوزات المعلقة',
      confirmedBookings: 'الحجوزات المؤكدة',
      cancelledBookings: 'الحجوزات الملغية',
      completedBookings: 'الحجوزات المكتملة',
      
      // Package Management
      packageManagement: 'إدارة الباقات',
      addNewPackage: 'إضافة باقة جديدة',
      packageName: 'اسم الباقة',
      packageDescription: 'وصف الباقة',
      packagePrice: 'سعر الباقة',
      packageDuration: 'مدة الباقة',
      packageStatus: 'حالة الباقة',
      active: 'نشط',
      inactive: 'غير نشط',
      featured: 'مميز',
      editPackage: 'تعديل الباقة',
      deletePackage: 'حذف الباقة',
      packageDetails: 'تفاصيل الباقة',
      inclusions: 'المشمولات',
      exclusions: 'غير المشمولات',
      itinerary: 'البرنامج',
      requirements: 'المتطلبات',
      availability: 'التوفر',
      
      // Booking Management
      bookingManagement: 'إدارة الحجوزات',
      bookingId: 'رقم الحجز',
      customerName: 'اسم العميل',
      packageName: 'اسم الباقة',
      bookingDate: 'تاريخ الحجز',
      travelDate: 'تاريخ السفر',
      totalAmount: 'المبلغ الإجمالي',
      bookingStatus: 'حالة الحجز',
      paymentStatus: 'حالة الدفع',
      pending: 'معلق',
      confirmed: 'مؤكد',
      cancelled: 'ملغي',
      completed: 'مكتمل',
      paid: 'مدفوع',
      unpaid: 'غير مدفوع',
      refunded: 'مسترد',
      failed: 'فشل',
      viewBooking: 'عرض الحجز',
      editBooking: 'تعديل الحجز',
      updateStatus: 'تحديث الحالة',
      sendNotification: 'إرسال إشعار',
      
      // User Management
      userManagement: 'إدارة المستخدمين',
      addNewUser: 'إضافة مستخدم جديد',
      userRole: 'دور المستخدم',
      admin: 'مدير',
      staff: 'موظف',
      user: 'مستخدم',
      userStatus: 'حالة المستخدم',
      lastLogin: 'آخر تسجيل دخول',
      joinDate: 'تاريخ الانضمام',
      editUser: 'تعديل المستخدم',
      deleteUser: 'حذف المستخدم',
      userPermissions: 'صلاحيات المستخدم',
      canManageUsers: 'يمكن إدارة المستخدمين',
      canManageBookings: 'يمكن إدارة الحجوزات',
      canManagePackages: 'يمكن إدارة الباقات',
      canManageContent: 'يمكن إدارة المحتوى',
      canViewAnalytics: 'يمكن عرض التحليلات',
      canManageSettings: 'يمكن إدارة الإعدادات',
      
      // Content Management
      contentManagement: 'إدارة المحتوى',
      pages: 'الصفحات',
      addNewPage: 'إضافة صفحة جديدة',
      pageTitle: 'عنوان الصفحة',
      pageContent: 'محتوى الصفحة',
      pageStatus: 'حالة الصفحة',
      published: 'منشور',
      draft: 'مسودة',
      editPage: 'تعديل الصفحة',
      deletePage: 'حذف الصفحة',
      translations: 'الترجمات',
      addTranslation: 'إضافة ترجمة',
      translationKey: 'مفتاح الترجمة',
      englishText: 'النص الإنجليزي',
      arabicText: 'النص العربي',
      frenchText: 'النص الفرنسي',
      editTranslation: 'تعديل الترجمة',
      deleteTranslation: 'حذف الترجمة',
      
      // Analytics & Reports
      analyticsReports: 'التحليلات والتقارير',
      revenueAnalytics: 'تحليل الإيرادات',
      bookingAnalytics: 'تحليل الحجوزات',
      userAnalytics: 'تحليل المستخدمين',
      packageAnalytics: 'تحليل الباقات',
      generateReport: 'إنشاء تقرير',
      reportType: 'نوع التقرير',
      dateRange: 'نطاق التاريخ',
      exportReport: 'تصدير التقرير',
      downloadReport: 'تحميل التقرير',
      reportPeriod: 'فترة التقرير',
      lastWeek: 'الأسبوع الماضي',
      lastMonth: 'الشهر الماضي',
      lastQuarter: 'الربع الماضي',
      lastYear: 'السنة الماضية',
      customRange: 'نطاق مخصص',
      
      // Settings
      settings: 'الإعدادات',
      generalSettings: 'الإعدادات العامة',
      siteSettings: 'إعدادات الموقع',
      emailSettings: 'إعدادات البريد الإلكتروني',
      securitySettings: 'إعدادات الأمان',
      notificationSettings: 'إعدادات الإشعارات',
      backupSettings: 'إعدادات النسخ الاحتياطي',
      siteName: 'اسم الموقع',
      siteDescription: 'وصف الموقع',
      contactEmail: 'البريد الإلكتروني للاتصال',
      contactPhone: 'رقم الهاتف للاتصال',
      address: 'العنوان',
      currency: 'العملة',
      timezone: 'المنطقة الزمنية',
      dateFormat: 'تنسيق التاريخ',
      language: 'اللغة',
      enableNotifications: 'تفعيل الإشعارات',
      emailNotifications: 'إشعارات البريد الإلكتروني',
      smsNotifications: 'إشعارات الرسائل النصية',
      maintenanceMode: 'وضع الصيانة',
      allowRegistration: 'السماح بالتسجيل',
      requireEmailVerification: 'تطلب التحقق من البريد الإلكتروني',
      maxFileSize: 'الحد الأقصى لحجم الملف',
      allowedFileTypes: 'أنواع الملفات المسموحة',
      saveSettings: 'حفظ الإعدادات',
      resetSettings: 'إعادة تعيين الإعدادات',
      backupData: 'نسخ احتياطي للبيانات',
      restoreData: 'استعادة البيانات',
      
      // Additional Dashboard Texts
      fromLastMonth: 'من الشهر الماضي',
      fromLastPeriod: 'من الفترة الماضية',
      confirmed: 'مؤكد',
      pending: 'معلق',
      cancelled: 'ملغي',
      premiumHajjPackage2024: 'باقة الحج المميزة 2024',
      luxuryUmrahPackage: 'باقة العمرة الفاخرة',
      europeanCulturalHeritageTour: 'جولة التراث الثقافي الأوروبي',
      familyUmrahPackage: 'باقة العمرة العائلية',
      viewBookings: 'عرض الحجوزات',
      manageYourTravelPackages: 'إدارة باقات السفر الخاصة بك',
      edit: 'تعديل',
      view: 'عرض',
      delete: 'حذف',
      duration: 'المدة',
      price: 'السعر',
      bookings: 'الحجوزات',
      revenue: 'الإيرادات',
      status: 'الحالة',
      actions: 'الإجراءات',
      active: 'نشط',
      manageCustomerBookings: 'إدارة حجوزات العملاء',
      amount: 'المبلغ',
      payment: 'الدفع',
      manageCustomersAndStaff: 'إدارة العملاء والموظفين',
      totalCustomers: 'إجمالي العملاء',
      activeCustomers: 'العملاء النشطون',
      staffMembers: 'أعضاء الفريق',
      trackBusinessPerformance: 'تتبع أداء الأعمال',
      bookingsByType: 'الحجوزات حسب النوع',
      topPerformingPackages: 'أفضل الباقات أداءً',
      customerInsights: 'رؤى العملاء',
      newCustomers: 'عملاء جدد',
      returningCustomers: 'العملاء العائدون',
      averageAge: 'متوسط العمر',
      topCountries: 'أفضل البلدان',
      configureWebsiteSettings: 'تكوين إعدادات الموقع',
      appearance: 'المظهر',
      notifications: 'الإشعارات',
      security: 'الأمان',
      emailSettings: 'إعدادات البريد الإلكتروني',
      backupRestore: 'النسخ الاحتياطي والاستعادة',
      allowUserRegistration: 'السماح بتسجيل المستخدمين',
      allowNewUsersToRegister: 'السماح للمستخدمين الجدد بتسجيل الحسابات',
      requireEmailVerification: 'تطلب من المستخدمين التحقق من عناوين بريدهم الإلكتروني',
      
      // Additional Status and Value Translations
      paid: 'مدفوع',
      refunded: 'مسترد',
      active: 'نشط',
      inactive: 'غير نشط',
      avgBookingValue: 'متوسط قيمة الحجز',
      confirmed: 'مؤكد',
      pending: 'معلق',
      cancelled: 'ملغي',
      modifier: 'المعدل',
      copy: 'نسخ',
      conversionRate: 'معدل التحويل',
      temporarilyDisablePublicAccess: 'تعطيل الوصول العام للموقع مؤقتاً',
      allowNewUsersToRegister: 'السماح للمستخدمين الجدد بتسجيل الحسابات',
      requireUsersToVerifyEmail: 'تطلب من المستخدمين التحقق من عناوين بريدهم الإلكتروني',
      fileUploadSettings: 'إعدادات رفع الملفات',
      maximumFileSize: 'الحد الأقصى لحجم الملف',
      receiveEmailNotifications: 'تلقي إشعارات البريد الإلكتروني للأحداث المهمة',
      receiveSmsNotifications: 'تلقي إشعارات الرسائل النصية للتحديثات العاجلة'
    },
    
    fr: {
      // Navigation
      home: 'Accueil',
      hajjUmrah: 'Hajj et Omra',
      globalTourism: 'Tourisme Mondial',
      contact: 'Contact',
      bookNow: 'Réserver Maintenant',
      account: 'Compte',
      darkMode: 'Mode Sombre',
      lightMode: 'Mode Clair',
      selectLanguage: 'Sélectionner la Langue',
      
      // Homepage
      heroTitle: 'Votre Voyage Commence Ici',
      heroSubtitle: 'Découvrez les pèlerinages les plus sacrés du monde et des destinations à couper le souffle avec Al-Hijrah Tourism - votre partenaire de confiance pour les voyages spirituels et culturels.',
      exploreHajjUmrah: 'Explorer Hajj et Omra',
      discoverGlobalTours: 'Découvrir les Tours Mondiaux',
      ourServices: 'Nos Services',
      servicesSubtitle: 'Nous fournissons des solutions de voyage complètes adaptées à vos besoins spirituels et culturels',
      hajjUmrahService: 'Hajj et Omra',
      hajjUmrahDesc: 'Voyages spirituels complets avec guidage expert et hébergement premium',
      globalTourismService: 'Tourisme Mondial',
      globalTourismDesc: 'Explorez le monde avec nos forfaits de voyage et expériences soigneusement sélectionnés',
      expertGuidance: 'Guidage Expert',
      expertGuidanceDesc: 'Conseillers en voyage professionnels pour assurer que votre voyage soit fluide et mémorable',
      bestPrices: 'Meilleurs Prix',
      bestPricesDesc: 'Prix compétitifs sans frais cachés et options de paiement flexibles',
      specialOffers: 'Offres Spéciales',
      specialOffersSubtitle: 'Ne manquez pas ces offres à durée limitée',
      whyChooseUs: 'Pourquoi Choisir Al-Hijrah Tourism?',
      expertGuidanceFeature: 'Guidage Expert',
      expertGuidanceFeatureDesc: 'Notre équipe expérimentée fournit un guidage personnalisé pour chaque étape de votre voyage',
      premiumAccommodations: 'Hébergement Premium',
      premiumAccommodationsDesc: 'Séjournez dans des hôtels et hébergements soigneusement sélectionnés pour un confort maximum',
      support247: 'Support 24/7',
      support247Desc: 'Assistance 24h/24 pour assurer que votre voyage soit fluide et sans souci',
      readyToStart: 'Prêt à Commencer Votre Voyage?',
      readyToStartSubtitle: 'Contactez-nous aujourd\'hui pour planifier votre voyage spirituel ou culturel parfait',
      bookYourTrip: 'Réserver Votre Voyage',
      getInTouch: 'Entrer en Contact',
      
      // Additional French translations (no duplicates)
      visaAssistance: 'Assistance Visa',
      cancel: 'Annuler',
      customer: 'Client',
      emailAddress: 'Adresse Email',
      phoneNumber: 'Numéro de Téléphone',
      email: 'Email',
      totalSpent: 'Total Dépensé',
      fullName: 'Nom Complet',
      address: 'Adresse',
      overview: 'Aperçu',
      totalBookings: 'Total des Réservations',
      recentBookings: 'Réservations Récentes',
      bookingId: 'ID de Réservation',
      travelDate: 'Date de Voyage',
      packageType: 'Type de Forfait',
      userType: 'Type d\'Utilisateur',
      addUser: 'Ajouter Utilisateur',
      totalPageViews: 'Total des Vues de Page',
      publishedPages: 'Pages Publiées',
      draftPages: 'Pages Brouillon',
      
      // Special Offers
      earlyBirdHajj2024: 'Hajj Early Bird 2024',
      earlyBirdHajjDesc: 'Réservez votre voyage Hajj maintenant et économisez jusqu\'à 15% sur les forfaits premium',
      umrahSpecialPackage: 'Forfait Omra Spécial',
      umrahSpecialDesc: 'Expérience Omra complète avec hébergement 5 étoiles et visites guidées',
      europeanSummerTour: 'Tour d\'Été Européen',
      europeanSummerDesc: 'Explorez la beauté de l\'Europe avec nos forfaits d\'été soigneusement sélectionnés',
      march31_2024: '31 Mars 2026',
      april15_2024: '15 Avril 2026',
      may30_2024: '30 Mai 2026',
      
      // Booking Form Translations
      bookYourJourney: 'Réservez Votre Voyage',
      completeFormToReserve: 'Complétez le formulaire pour réserver votre place',
      serviceSelection: 'Sélection du Service',
      personalInformation: 'Informations Personnelles',
      travelDetails: 'Détails du Voyage',
      emergencyContact: 'Contact d\'Urgence',
      paymentConfirmation: 'Confirmation de Paiement',
      submitBooking: 'Soumettre la Réservation',
      selectYourService: 'Sélectionnez Votre Service',
      serviceType: 'Type de Service',
      selectPackage: 'Sélectionner le Forfait',
      firstName: 'Prénom',
      lastName: 'Nom de Famille',
      email: 'Email',
      phone: 'Téléphone',
      departureCity: 'Ville de Départ',
      preferredDepartureDate: 'Date de Départ Préférée',
      returnDate: 'Date de Retour',
      numberOfTravelers: 'Nombre de Voyageurs',
      roomType: 'Type de Chambre',
      singleRoom: 'Chambre Simple',
      doubleRoom: 'Chambre Double',
      tripleRoom: 'Chambre Triple',
      quadRoom: 'Chambre Quadruple',
      specialRequests: 'Demandes Spéciales',
      travelInsurance: 'Assurance Voyage',
      visaAssistance: 'Assistance Visa',
      airportTransfer: 'Transfert Aéroport',
      additionalServices: 'Services Supplémentaires',
      agreeToTerms: 'J\'accepte les termes et conditions',
      nextStep: 'Étape Suivante',
      previousStep: 'Étape Précédente',
      totalCost: 'Coût Total',
      perPerson: 'par personne',
      selectDate: 'Sélectionner la Date',
      enterCity: 'Entrer la Ville',
      enterPhone: 'Entrer le Téléphone',
      enterEmail: 'Entrer l\'Email',
      required: 'Requis',
      optional: 'Optionnel',
      
      // Additional Form Field Translations
      selectServiceType: 'Sélectionner le Type de Service',
      package: 'Forfait',
      phoneNumber: 'Numéro de Téléphone',
      person: 'personne',
      people: 'personnes',
      selectRoomType: 'Sélectionner le Type de Chambre',
      bookingSummary: 'Résumé de la Réservation',
      travelers: 'Voyageurs',
      basePrice: 'Prix de Base',
      total: 'Total',
      previous: 'Précédent',
      next: 'Suivant',
      
      // Additional Services
      extraBaggageAllowance: 'Supplément Bagages',
      seatSelection: 'Sélection de Siège',
      mealUpgrade: 'Amélioration des Repas',
      inFlightWifi: 'WiFi en Vol',
      
      // Payment Methods
      creditCard: 'Carte de Crédit',
      debitCard: 'Carte de Débit',
      bankTransfer: 'Virement Bancaire',
      installments: 'Versements',
      
      // Placeholders and Help Text
      placeholderDepartureCity: 'ex: New York, Londres, Dubaï',
      placeholderSpecialRequests: 'Toute exigence alimentaire spéciale, besoin d\'accessibilité, ou autres demandes...',
      
      // Service Types
      hajj: 'Hajj',
      umrah: 'Omra',
      globalTourism: 'Tourisme Mondial',
      
      // Package Names
      premiumHajjPackage2024: 'Forfait Hajj Premium 2024',
      standardHajjPackage2024: 'Forfait Hajj Standard 2024',
      economyHajjPackage2024: 'Forfait Hajj Économique 2024',
      luxuryUmrahPackage: 'Forfait Omra de Luxe',
      familyUmrahPackage: 'Forfait Omra Familial',
      quickUmrahPackage: 'Forfait Omra Rapide',
      europeanCulturalHeritageTour: 'Tour du Patrimoine Culturel Européen',
      southeastAsiaAdventure: 'Aventure Asie du Sud-Est',
      africanSafariExperience: 'Expérience Safari Africain',
      
      // Admin Dashboard Translations
      dashboardOverview: 'Aperçu du Tableau de Bord',
      totalBookings: 'Total des Réservations',
      totalRevenue: 'Revenus Totaux',
      activePackages: 'Forfaits Actifs',
      registeredUsers: 'Utilisateurs Inscrits',
      recentBookings: 'Réservations Récentes',
      topPackages: 'Meilleurs Forfaits',
      revenueChart: 'Graphique des Revenus',
      bookingTrends: 'Tendances des Réservations',
      monthlyRevenue: 'Revenus Mensuels',
      bookingStatus: 'Statut de Réservation',
      pendingBookings: 'Réservations en Attente',
      confirmedBookings: 'Réservations Confirmées',
      cancelledBookings: 'Réservations Annulées',
      completedBookings: 'Réservations Terminées',
      
      // Package Management
      packageManagement: 'Gestion des Forfaits',
      addNewPackage: 'Ajouter un Nouveau Forfait',
      packageName: 'Nom du Forfait',
      packageDescription: 'Description du Forfait',
      packagePrice: 'Prix du Forfait',
      packageDuration: 'Durée du Forfait',
      packageStatus: 'Statut du Forfait',
      active: 'Actif',
      inactive: 'Inactif',
      featured: 'En Vedette',
      editPackage: 'Modifier le Forfait',
      deletePackage: 'Supprimer le Forfait',
      packageDetails: 'Détails du Forfait',
      inclusions: 'Inclusions',
      exclusions: 'Exclusions',
      itinerary: 'Itinéraire',
      requirements: 'Exigences',
      availability: 'Disponibilité',
      
      // Booking Management
      bookingManagement: 'Gestion des Réservations',
      bookingId: 'ID de Réservation',
      customerName: 'Nom du Client',
      packageName: 'Nom du Forfait',
      bookingDate: 'Date de Réservation',
      travelDate: 'Date de Voyage',
      totalAmount: 'Montant Total',
      bookingStatus: 'Statut de Réservation',
      paymentStatus: 'Statut de Paiement',
      pending: 'En Attente',
      confirmed: 'Confirmé',
      cancelled: 'Annulé',
      completed: 'Terminé',
      paid: 'Payé',
      unpaid: 'Impayé',
      refunded: 'Remboursé',
      failed: 'Échoué',
      viewBooking: 'Voir la Réservation',
      editBooking: 'Modifier la Réservation',
      updateStatus: 'Mettre à Jour le Statut',
      sendNotification: 'Envoyer une Notification',
      
      // User Management
      userManagement: 'Gestion des Utilisateurs',
      addNewUser: 'Ajouter un Nouvel Utilisateur',
      userRole: 'Rôle Utilisateur',
      admin: 'Admin',
      staff: 'Personnel',
      user: 'Utilisateur',
      userStatus: 'Statut Utilisateur',
      lastLogin: 'Dernière Connexion',
      joinDate: 'Date d\'Adhésion',
      editUser: 'Modifier l\'Utilisateur',
      deleteUser: 'Supprimer l\'Utilisateur',
      userPermissions: 'Permissions Utilisateur',
      canManageUsers: 'Peut Gérer les Utilisateurs',
      canManageBookings: 'Peut Gérer les Réservations',
      canManagePackages: 'Peut Gérer les Forfaits',
      canManageContent: 'Peut Gérer le Contenu',
      canViewAnalytics: 'Peut Voir les Analyses',
      canManageSettings: 'Peut Gérer les Paramètres',
      
      // Content Management
      contentManagement: 'Gestion du Contenu',
      pages: 'Pages',
      addNewPage: 'Ajouter une Nouvelle Page',
      pageTitle: 'Titre de la Page',
      pageContent: 'Contenu de la Page',
      pageStatus: 'Statut de la Page',
      published: 'Publié',
      draft: 'Brouillon',
      editPage: 'Modifier la Page',
      deletePage: 'Supprimer la Page',
      translations: 'Traductions',
      addTranslation: 'Ajouter une Traduction',
      translationKey: 'Clé de Traduction',
      englishText: 'Texte Anglais',
      arabicText: 'Texte Arabe',
      frenchText: 'Texte Français',
      editTranslation: 'Modifier la Traduction',
      deleteTranslation: 'Supprimer la Traduction',
      
      // Analytics & Reports
      analyticsReports: 'Analyses et Rapports',
      revenueAnalytics: 'Analyse des Revenus',
      bookingAnalytics: 'Analyse des Réservations',
      userAnalytics: 'Analyse des Utilisateurs',
      packageAnalytics: 'Analyse des Forfaits',
      generateReport: 'Générer un Rapport',
      reportType: 'Type de Rapport',
      dateRange: 'Plage de Dates',
      exportReport: 'Exporter le Rapport',
      downloadReport: 'Télécharger le Rapport',
      reportPeriod: 'Période du Rapport',
      lastWeek: 'Semaine Dernière',
      lastMonth: 'Mois Dernier',
      lastQuarter: 'Trimestre Dernier',
      lastYear: 'Année Dernière',
      customRange: 'Plage Personnalisée',
      
      // Settings
      settings: 'Paramètres',
      generalSettings: 'Paramètres Généraux',
      siteSettings: 'Paramètres du Site',
      emailSettings: 'Paramètres Email',
      securitySettings: 'Paramètres de Sécurité',
      notificationSettings: 'Paramètres de Notification',
      backupSettings: 'Paramètres de Sauvegarde',
      siteName: 'Nom du Site',
      siteDescription: 'Description du Site',
      contactEmail: 'Email de Contact',
      contactPhone: 'Téléphone de Contact',
      address: 'Adresse',
      currency: 'Devise',
      timezone: 'Fuseau Horaire',
      dateFormat: 'Format de Date',
      language: 'Langue',
      enableNotifications: 'Activer les Notifications',
      emailNotifications: 'Notifications Email',
      smsNotifications: 'Notifications SMS',
      maintenanceMode: 'Mode Maintenance',
      allowRegistration: 'Autoriser l\'Inscription',
      requireEmailVerification: 'Exiger la Vérification Email',
      maxFileSize: 'Taille Max du Fichier',
      allowedFileTypes: 'Types de Fichiers Autorisés',
      saveSettings: 'Sauvegarder les Paramètres',
      resetSettings: 'Réinitialiser les Paramètres',
      backupData: 'Sauvegarder les Données',
      restoreData: 'Restaurer les Données',
      
      // Additional Dashboard Texts
      fromLastMonth: 'du Mois Dernier',
      fromLastPeriod: 'de la Période Précédente',
      confirmed: 'Confirmé',
      pending: 'En Attente',
      cancelled: 'Annulé',
      premiumHajjPackage2024: 'Forfait Hajj Premium 2024',
      luxuryUmrahPackage: 'Forfait Omra de Luxe',
      europeanCulturalHeritageTour: 'Tour du Patrimoine Culturel Européen',
      familyUmrahPackage: 'Forfait Omra Familial',
      viewBookings: 'Voir les Réservations',
      manageYourTravelPackages: 'Gérer vos Forfaits de Voyage',
      edit: 'Modifier',
      view: 'Voir',
      delete: 'Supprimer',
      duration: 'Durée',
      price: 'Prix',
      bookings: 'Réservations',
      revenue: 'Revenus',
      status: 'Statut',
      actions: 'Actions',
      active: 'Actif',
      manageCustomerBookings: 'Gérer les Réservations Clients',
      amount: 'Montant',
      payment: 'Paiement',
      manageCustomersAndStaff: 'Gérer les Clients et le Personnel',
      totalCustomers: 'Total Clients',
      activeCustomers: 'Clients Actifs',
      staffMembers: 'Membres du Personnel',
      trackBusinessPerformance: 'Suivre les Performances Commerciales',
      bookingsByType: 'Réservations par Type',
      topPerformingPackages: 'Meilleurs Forfaits Performants',
      customerInsights: 'Insights Clients',
      newCustomers: 'Nouveaux Clients',
      returningCustomers: 'Clients de Retour',
      averageAge: 'Âge Moyen',
      topCountries: 'Top Pays',
      configureWebsiteSettings: 'Configurer les Paramètres du Site',
      appearance: 'Apparence',
      notifications: 'Notifications',
      security: 'Sécurité',
      emailSettings: 'Paramètres Email',
      backupRestore: 'Sauvegarde et Restauration',
      allowUserRegistration: 'Autoriser l\'Inscription Utilisateur',
      allowNewUsersToRegister: 'Autoriser les nouveaux utilisateurs à s\'inscrire',
      requireEmailVerification: 'Exiger des utilisateurs de vérifier leurs adresses email',
      
      // Additional Status and Value Translations
      paid: 'Payé',
      refunded: 'Remboursé',
      active: 'Actif',
      inactive: 'Inactif',
      avgBookingValue: 'Valeur Moyenne de Réservation',
      confirmed: 'Confirmé',
      pending: 'En Attente',
      cancelled: 'Annulé',
      modifier: 'Modificateur',
      copy: 'Copier',
      conversionRate: 'Taux de Conversion',
      temporarilyDisablePublicAccess: 'Désactiver temporairement l\'accès public au site web',
      allowNewUsersToRegister: 'Autoriser les nouveaux utilisateurs à s\'inscrire',
      requireUsersToVerifyEmail: 'Exiger des utilisateurs de vérifier leurs adresses email',
      fileUploadSettings: 'Paramètres de Téléchargement de Fichiers',
      maximumFileSize: 'Taille Maximale du Fichier',
      receiveEmailNotifications: 'Recevoir des notifications email pour les événements importants',
      receiveSmsNotifications: 'Recevoir des notifications SMS pour les mises à jour urgentes'
    }
  };

  // Translation function
  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  // Get current language info
  const getCurrentLanguage = () => {
    return languages.find(lang => lang.code === language) || languages[0];
  };

  // Change language function
  const changeLanguage = (langCode) => {
    setLanguage(langCode);
    localStorage.setItem('language', langCode);
    setIsLanguageDropdownOpen(false);
  };

  // Toggle dark mode
  const toggleDarkMode = () => {
    const newDarkMode = !isDarkMode;
    setIsDarkMode(newDarkMode);
    localStorage.setItem('darkMode', JSON.stringify(newDarkMode));
  };

  // Save dark mode preference and apply to document
  useEffect(() => {
    localStorage.setItem('darkMode', JSON.stringify(isDarkMode));
    
    // Apply dark mode class to document
    if (isDarkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [isDarkMode]);

  // Save language preference
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const value = {
    // State
    isDarkMode,
    language,
    isLanguageDropdownOpen,
    
    // Data
    languages,
    
    // Functions
    t,
    toggleDarkMode,
    changeLanguage,
    getCurrentLanguage,
    setIsLanguageDropdownOpen
  };

  return (
    <AppContext.Provider value={value}>
      {children}
    </AppContext.Provider>
  );
};